### ISSUE TITLE
Suggestion: extend fetch

### ISSUE THREAD

**Issue by marciolegal** [wkearn/RasterIO.jl#19]
Hi,

That way one could simply use `fetch(raster)` instead of `RasterIO.fetch(raster)`. At the moment, using `fetch(raster)` doesn't error out and returns the same Raster object which is not very helpful and can possibly create confusion by users in the future.
If you agree with this I will try to make this work for all fetch methods and make a PR this weekend.

**Comment by yeesian** [comment]
Exporting names is easy. But we haven't yet decided whether we really want to settle on the method names `fetch` and `update`, or to disambiguate them from base julia methods by renaming them to `fetchraster` and `updateraster` (like the other IO methods instead).

**Comment by marciolegal** [comment]
If not planing future special functionality for these base functions, renaming them Base.fetch and Base.update sounds like a good option. Better integration with the Language, somewhat like R works. Does it make sense in Julia?
