### ISSUE TITLE
Install dependencies with BinDeps

### ISSUE THREAD

**Issue by wkearn** [wkearn/RasterIO.jl#2]
GDAL needs to be installed as a prerequisite. BinDeps should be able to do this easily; GDAL isn't a very complicated library. I'm just not greatly familiar with the BinDeps API at the moment.

**Comment by meggart** [comment]
I don't know if you have seen this but I once opened this issue to get a GDAL bottle to make BinDeps work on Macs: https://github.com/JuliaLang/Homebrew.jl/issues/44 
However, last time I tried installing Binaries via Homebrew it did not work but I wasn't sure if it was an internet connectivity problem...

**Comment by yeesian** [comment]
closed by #11
